@node talk invocation
@chapter @command{talk}: a communication program
@cindex talk

@command{Talk} is a visual communication program which copies lines from
your terminal to that of another user.

@section Invoking

The command line arguments are as follows:

@table @var

@item person
If you wish to talk to someone on your own machine, then person
is just the person's login name.  If you wish to talk to a user
on another host, then person is of the form @samp{user@@host}.

@item ttyname
If you wish to talk to a user who is logged in more than once,
the @var{ttyname} argument may be used to indicate the appropriate
terminal name, where @var{ttyname} is of the form @samp{ttyXX}.

@end table

When first called, talk sends the message
@example
           Message from TalkDaemon@@his_machine...
           talk: connection requested by your_name@@your_machine.
           talk: respond with: talk your_name@@your_machine
@end example

to the user you wish to talk to. At this point, the recipient of the message
should reply by typing
@example
           talk  your_name@@your_machine
@end example

It doesn't matter from which machine the recipient replies, as long as
his login-name is the same.  Once communication is established, the two
parties may type simultaneously, with their output appearing in separate
windows.  Typing @kbd{C-L} will cause the screen to be reprinted,
while your erase, kill, and word kill characters will behave normally.
To exit, just type your interrupt character; talk then moves the cursor
to the bottom of the screen and restores the terminal to its previous state.

Permission to talk may be denied or granted by use of the
@command{mesg}(1) command.  At the outset talking is allowed.  Certain
commands, in particular @command{nroff}(1) and @command{pr}(1),
disallow messages in order to prevent messy output. 

To exit, just type your interrupt character; talk then moves the cursor
to the bottom of the screen and restores the terminal to its previous state.

