@node traceroute invocation
@chapter @command{traceroute}: Trace the route to a host.
@pindex traceroute

@command{Traceroute} traces the route packets take to a host.

@example
traceroute [@var{option}]@dots{} [@var{host}]
@end example

@table @option

@item -M @var{method}
@itemx --type=@var{method}
@opindex -M
@opindex --type
Use @var{method} (@samp{icmp} or @samp{udp}) for traceroute operations.

@item -p @var{port}
@itemx --port=@var{port}
@opindex -p
@opindex --port
Use destination @var{port} (default: 33434).

@item -q @var{num}
@itemx --tries=@var{num}
@opindex -q
@opindex --tries
Send @var{num} probe packets per hop (default: 3).

@item --resolve-hostnames
@opindex --resolve-hostnames
Resolve hostnames.

@end table
