char *whois_servers =
"# This is the configuration file for the GNU whois client; it lists the\n"
"# pattern for a whois query on the left, and the whois server on the right.\n"
"# Comments start with # characters and go to the end of the line.\n"
"#\n"
"# If a server name is specified by an @ in the name to look up or with the\n"
"# -h option, that will be used.  If those options don't provide any server\n"
"# specification, then configuration files will be searched in this order, and\n"
"# the first match will be used: the file specified by --config-file,\n"
"# $HOME/.whois-servers, $SYSCONFDIR/whois-servers,\n"
"# $DATADIR/inet/whois-servers, and finally the version of the config file\n"
"# that is supplied with the inetutils that is compiled into the whois binary.\n"
"#\n"
"# Unless something bizarre happens on your system, the compiled in config\n"
"# file is identical to $DATADIR/inet/whois-servers.\n"
"#\n"
"# It is recommended that if you want to locally override the list of whois\n"
"# servers, you put your list in $SYSCONFDIR, so that you can install a new\n"
"# version of the inetutils without having your configuration clobbered.\n"
"\n"
"*-arin		whois.arin.net\n"
"[0-9]*		whois.arin.net\n"
"*.mil		nic.ddn.net\n"
"*		whois.internic.net\n"
;
